export let NameDays = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']
export let Schedule = [
    { day: 1, tasks: [{color: 'green'}]},
    { day: 2, tasks: []},
    { day: 3, tasks: []},
    { day: 4, tasks: []},
    { day: 5, tasks: []},
    { day: 6, tasks: []},
    { day: 7, tasks: []},
    { day: 8, tasks: []},
    { day: 9, tasks: []},
    { day: 10, tasks: []},
    { day: 11, tasks: []},
    { day: 12, tasks: []},
    { day: 13, tasks: []},
    { day: 14, tasks: []},
    { day: 15, tasks: []},
    { day: 16, tasks: []},
    { day: 17, tasks: []},
    { day: 18, tasks: []},
    { day: 19, tasks: [{color: '#c4d'}]},
    { day: 20, tasks: []},
    { day: 21, tasks: []},
    { day: 22, tasks: []},
    { day: 23, tasks: []},
    { day: 24, tasks: []},
    { day: 25, tasks: []},
    { day: 26, tasks: []},
    { day: 27, tasks: []},
    { day: 28, tasks: []},
]